CREATE TABLE IF NOT EXISTS briskula_games (
    id UUID NOT NULL,
    lobby_id UUID NOT NULL,
    name VARCHAR(255) NOT NULL,
    owner_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    game_type VARCHAR(50) NOT NULL,
    turn_end_time TIMESTAMP WITH TIME ZONE,
    turn_duration_seconds INTEGER,
    turn_number INTEGER NOT NULL,
    game_config VARCHAR(80) NOT NULL,
    trump_card_suit VARCHAR(30) NOT NULL,
    trump_card_value VARCHAR(30) NOT NULL,
    ended_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_briskula_games PRIMARY KEY (id),
    CONSTRAINT fk_briskula_games_owner
        FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_briskula_games_owner_id
    ON briskula_games (owner_id);

CREATE INDEX IF NOT EXISTS idx_briskula_games_lobby_id
    ON briskula_games (lobby_id);

CREATE TABLE IF NOT EXISTS briskula_game_players (
    briskula_game_id UUID NOT NULL,
    user_id BIGINT NOT NULL,
    player_order INTEGER NOT NULL,
    CONSTRAINT pk_briskula_game_players PRIMARY KEY (briskula_game_id, player_order),
    CONSTRAINT uk_briskula_game_players_game_user UNIQUE (briskula_game_id, user_id),
    CONSTRAINT fk_briskula_game_players_game
        FOREIGN KEY (briskula_game_id) REFERENCES briskula_games (id),
    CONSTRAINT fk_briskula_game_players_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_briskula_game_players_user_id
    ON briskula_game_players (user_id);

CREATE TABLE IF NOT EXISTS briskula_playing_fields (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    briskula_game_id UUID NOT NULL,
    field_order INTEGER NOT NULL,
    played_cards VARCHAR(32) NOT NULL,
    played_player_ids VARCHAR(255) NOT NULL,
    player_hands VARCHAR(512) NOT NULL,
    winner_user_id BIGINT,
    total_points INTEGER,
    CONSTRAINT pk_briskula_playing_fields PRIMARY KEY (id),
    CONSTRAINT uk_briskula_playing_fields_game_order UNIQUE (briskula_game_id, field_order),
    CONSTRAINT fk_briskula_playing_fields_game
        FOREIGN KEY (briskula_game_id) REFERENCES briskula_games (id),
    CONSTRAINT fk_briskula_playing_fields_winner
        FOREIGN KEY (winner_user_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_briskula_playing_fields_game_id
    ON briskula_playing_fields (briskula_game_id);

CREATE TABLE IF NOT EXISTS briskula_game_team_players (
    briskula_game_id UUID NOT NULL,
    user_id BIGINT NOT NULL,
    player_order INTEGER NOT NULL,
    CONSTRAINT pk_briskula_game_team_players PRIMARY KEY (briskula_game_id, player_order),
    CONSTRAINT uk_briskula_game_team_players_game_user UNIQUE (briskula_game_id, user_id),
    CONSTRAINT fk_briskula_game_team_players_game
        FOREIGN KEY (briskula_game_id) REFERENCES briskula_games (id),
    CONSTRAINT fk_briskula_game_team_players_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_briskula_game_team_players_user_id
    ON briskula_game_team_players (user_id);
