CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(320) NOT NULL,
    username VARCHAR(50) NOT NULL,
    enabled BOOLEAN NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_login TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL,
    role VARCHAR(32) NOT NULL,
    CONSTRAINT uk_user_roles_user_role UNIQUE (user_id, role),
    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS tokens (
    id UUID NOT NULL,
    token VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    active BOOLEAN NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_tokens PRIMARY KEY (id),
    CONSTRAINT uk_tokens_token UNIQUE (token),
    CONSTRAINT fk_tokens_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_tokens_user_id
    ON tokens (user_id);

CREATE TABLE IF NOT EXISTS sessions (
    id UUID NOT NULL,
    user_id BIGINT,
    token_id UUID NOT NULL,
    device_id VARCHAR(255),
    client_type VARCHAR(255),
    os VARCHAR(255),
    ip_hash VARCHAR(255) NOT NULL,
    country VARCHAR(255),
    region VARCHAR(255),
    user_agent VARCHAR(512),
    first_seen_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_seen_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_authenticated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_sessions PRIMARY KEY (id),
    CONSTRAINT uk_sessions_token UNIQUE (token_id),
    CONSTRAINT fk_sessions_token
        FOREIGN KEY (token_id) REFERENCES tokens (id)
);

CREATE INDEX IF NOT EXISTS idx_sessions_user_id
    ON sessions (user_id);

CREATE TABLE IF NOT EXISTS verification_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code VARCHAR(255) NOT NULL,
    expiration_time TIMESTAMP WITH TIME ZONE NOT NULL,
    user_id BIGINT NOT NULL,
    used BOOLEAN NOT NULL,
    CONSTRAINT pk_verification_codes PRIMARY KEY (id),
    CONSTRAINT fk_verification_codes_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_verification_codes_user_id
    ON verification_codes (user_id);

CREATE TABLE IF NOT EXISTS user_game_stats (
    id UUID NOT NULL,
    user_id BIGINT,
    CONSTRAINT pk_user_game_stats PRIMARY KEY (id),
    CONSTRAINT uk_user_game_stats_user UNIQUE (user_id),
    CONSTRAINT fk_user_game_stats_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS user_game_stats_entries (
    user_game_stats_id UUID NOT NULL,
    game_type VARCHAR(255) NOT NULL,
    played INTEGER NOT NULL,
    wins INTEGER NOT NULL,
    CONSTRAINT pk_user_game_stats_entries PRIMARY KEY (user_game_stats_id, game_type),
    CONSTRAINT fk_user_game_stats_entries_user_game_stats
        FOREIGN KEY (user_game_stats_id) REFERENCES user_game_stats (id)
);

CREATE INDEX IF NOT EXISTS idx_user_game_stats_entries_user_game_stats_id
    ON user_game_stats_entries (user_game_stats_id);
