CREATE TABLE IF NOT EXISTS recorded_games
(
    id            UUID PRIMARY KEY,
    lobby_id      UUID                     NOT NULL,
    name          VARCHAR(255)             NOT NULL,
    owner_user_id BIGINT                   NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    started_at    TIMESTAMP WITH TIME ZONE,
    ended_at      TIMESTAMP WITH TIME ZONE
);
CREATE TABLE IF NOT EXISTS recorded_briskula_games
(
    id            UUID PRIMARY KEY REFERENCES recorded_games (id) ON DELETE CASCADE,
    game_config   VARCHAR(80) NOT NULL,
    teams_enabled BOOLEAN     NOT NULL,
    trump_suit    VARCHAR(30) NOT NULL,
    trump_value   VARCHAR(30) NOT NULL
);
CREATE TABLE IF NOT EXISTS recorded_game_players
(
    game_id      UUID         NOT NULL REFERENCES recorded_games (id) ON DELETE CASCADE,
    user_id      BIGINT       NOT NULL,
    name         VARCHAR(255) NOT NULL,
    player_order INTEGER      NOT NULL,
    PRIMARY KEY (game_id, player_order)
);
CREATE TABLE IF NOT EXISTS recorded_briskula_team_players
(
    game_id      UUID    NOT NULL REFERENCES recorded_briskula_games (id) ON DELETE CASCADE,
    user_id      BIGINT  NOT NULL,
    player_order INTEGER NOT NULL,
    PRIMARY KEY (game_id, player_order)
);
CREATE TABLE IF NOT EXISTS recorded_rounds
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id        UUID    NOT NULL REFERENCES recorded_games (id) ON DELETE CASCADE,
    round_order    INTEGER NOT NULL,
    winner_user_id BIGINT,
    winner_name    VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS recorded_plays
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round_id   BIGINT       NOT NULL REFERENCES recorded_rounds (id) ON DELETE CASCADE,
    play_order INTEGER      NOT NULL,
    user_id    BIGINT       NOT NULL,
    name       VARCHAR(255) NOT NULL,
    suit       VARCHAR(30)  NOT NULL,
    value      VARCHAR(30)  NOT NULL,
    number     INTEGER      NOT NULL
);
CREATE TABLE IF NOT EXISTS recorded_player_hands
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round_id   BIGINT       NOT NULL REFERENCES recorded_rounds (id) ON DELETE CASCADE,
    hand_order INTEGER      NOT NULL,
    user_id    BIGINT       NOT NULL,
    name       VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS recorded_hand_cards
(
    hand_id BIGINT      NOT NULL REFERENCES recorded_player_hands (id) ON DELETE CASCADE,
    suit    VARCHAR(30) NOT NULL,
    value   VARCHAR(30) NOT NULL,
    number  INTEGER     NOT NULL
);
CREATE TABLE IF NOT EXISTS recorded_game_attributes
(
    game_id         UUID         NOT NULL REFERENCES recorded_games (id) ON DELETE CASCADE,
    attribute_key   VARCHAR(255) NOT NULL,
    attribute_value VARCHAR(255),
    PRIMARY KEY (game_id, attribute_key)
);
CREATE TABLE IF NOT EXISTS recorded_round_attributes
(
    round_id        BIGINT       NOT NULL REFERENCES recorded_rounds (id) ON DELETE CASCADE,
    attribute_key   VARCHAR(255) NOT NULL,
    attribute_value VARCHAR(255),
    PRIMARY KEY (round_id, attribute_key)
);
CREATE INDEX IF NOT EXISTS idx_recorded_game_players_user_id ON recorded_game_players (user_id);
