# General info
app.title=ULTRACARDS Server
app.version=0.1.0
spring.profiles.default=dev

# DB settings shared across profiles
spring.jpa.database=postgresql
spring.sql.init.platform=postgres
spring.jpa.open-in-view=false
app.database.startup-check.enabled=true
app.database.startup-check.timeout-ms=3000

# Email settings shared across profiles
spring.mail.host=smtp.gmail.com
spring.mail.port=587
app.mail.from.name=ULTRACARDS
app.mail.startup-check.enabled=true
app.mail.startup-check.timeout-ms=5000
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}

# Token settings shared across profiles
app.token.duration-minutes=10
app.token.update-privilege-duration-minutes=5
app.cookie-token.duration-days=15
app.cookie-token.same-site=Lax

app.lobby.timer.duration-seconds=10
app.briskula-move.timer.duration-seconds=30

# Max Length Properties
# username maximum max-length is 50
app.max-length.username=30
# email maximum max-length is 320
app.max-length.email=150

# How long is verification code valid for. in minutes
app.verification-code.validity-minutes=15

spring.web.error.include-message=never
spring.web.error.include-binding-errors=never
spring.web.error.include-stacktrace=never
