spring.config.activate.on-profile=dev
spring.devtools.add-properties=true

# Local database
spring.datasource.url=jdbc:postgresql://localhost:5432/ultracards
spring.datasource.username=ultracards_user
spring.datasource.password=ultracards123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Development logging
logging.level.root=INFO
logging.level.com.ultracards=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.web.servlet.DispatcherServlet=OFF
logging.level.org.springframework.web.servlet.FrameworkServlet=OFF
logging.level.org.apache.catalina=ERROR
logging.level.com.zaxxer.hikari=ERROR
logging.level.org.hibernate.orm=ERROR
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.orm.jdbc.bind=TRACE

app.briskula-move.timer.duration-seconds=5
app.treseta-move.timer.duration-seconds=100
app.lobby.timer.duration-seconds=300


# Local cookies
app.cookie-token.secure=false
app.cookie-token.domain=
