# General info
app.title=ULTRACARDS server
app.version=0.1.0
app.debug=true

# DB settings
# Change the "ultracards" to the DB name
spring.datasource.url=jdbc:postgresql://localhost:5432/ultracards
# Add the username and the passwords that has permissions to access the DB
spring.datasource.username=your_db_user
spring.datasource.password=your_db_password
spring.jpa.database=postgresql
spring.sql.init.platform=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# Email settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your.email@gmail.com
app.mail.from.name=ULTRACARDS
# You have to generate an App password for this to work
spring.mail.password=your_app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Token Duration
app.token.duration-minutes=10
app.cookie-token.duration-days=15
app.cookie-token.same-site=Lax
app.cookie-token.secure=false
# Idk what it is used for yet, but I have implemented it
app.cookie-token.domain=

# Max Length Properties
# username maximum max-length is 50
app.max-length.username=30
# email maximum max-length is 320
app.max-length.email=150

# How long is verification code valid for. in minutes
app.verification-code.validity-minutes=15

# temporary
#spring.thymeleaf.cache=false
#spring.mvc.throw-exception-if-no-handler-found=true
#spring.web.resources.cache.cachecontrol.no-cache=true
#spring.web.resources.cache.cachecontrol.no-store=true
#spring.web.resources.cache.cachecontrol.must-revalidate=true
