spring.config.activate.on-profile=prod

spring.devtools.add-properties=false

# Production database
spring.datasource.url=jdbc:postgresql://localhost:5432/ultracards
spring.datasource.username=ultracards_user
spring.datasource.password=ultracards123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Production logging
logging.level.root=INFO
logging.level.com.ultracards=INFO
logging.level.org.springframework=WARN
logging.level.org.hibernate.SQL=WARN

# Production cookies
app.cookie-token.secure=true
app.cookie-token.domain=
