ultrakill.levels.prelude[0-1]=INTO THE FIRE
ultrakill.levels.prelude[0-2]=THE MEATGRINDER
ultrakill.levels.prelude[0-3]=DOUBLE DOWN
ultrakill.levels.prelude[0-4]=A ONE-MACHINE ARMY
ultrakill.levels.prelude[0-5]=CERBERUS

ultrakill.levels.act1[1-1]=HEART OF THE SUNRISE
ultrakill.levels.act1[1-2]=THE BURNING WORLD
ultrakill.levels.act1[1-3]=HALLS OF SACRED REMAINS
ultrakill.levels.act1[1-4]=CLAIR DE LUNE
ultrakill.levels.act1[2-1]=BRIDGEBURNER
ultrakill.levels.act1[2-2]=DEATH AT 20,000 VOLTS
ultrakill.levels.act1[2-3]=SHEER HEART ATTACK
ultrakill.levels.act1[2-4]=COURT OF THE CORPSE KING
ultrakill.levels.act1[3-1]=BELLY OF THE BEAST
ultrakill.levels.act1[3-2]=IN THE FLESH

ultrakill.levels.act2[4-1]=SLAVES TO POWER
ultrakill.levels.act2[4-2]=GOD DAMN THE SUN
ultrakill.levels.act2[4-3]=A SHOT IN THE DARK
ultrakill.levels.act2[4-4]=CLAIR DE SOLEIL
ultrakill.levels.act2[5-1]=IN THE WAKE OF POSEIDON
ultrakill.levels.act2[5-2]=WAVES OF THE STARLESS SEA
ultrakill.levels.act2[5-3]=SHIP OF FOOLS
ultrakill.levels.act2[5-4]=LEVIATHAN
ultrakill.levels.act2[6-1]=CRY FOR THE WEEPER
ultrakill.levels.act2[6-2]=AESTHETICS OF HATE

ultrakill.levels.act3[7-1]=GARDEN OF FORKING PATHS
ultrakill.levels.act3[7-2]=LIGHT UP THE NIGHT
ultrakill.levels.act3[7-3]=NO SOUND, NO MEMORY
ultrakill.levels.act3[7-4]=...LIKE ANTENNAS TO HEAVEN
ultrakill.levels.act3[8-1]=HURTBREAK WONDERLAND
ultrakill.levels.act3[8-2]=THROUGH THE MIRROR
ultrakill.levels.act3[8-3]=DISINTEGRATION LOOP
ultrakill.levels.act3[8-4]=FINAL FLIGHT
ultrakill.levels.act3[9-1]=???
ultrakill.levels.act3[9-2]=???

ultrakill.levels.finale[10-1]=???
ultrakill.levels.finale[10-2]=???

ultrakill.levels.primeSanctums[P-1]=SOUL SURVIVOR
ultrakill.levels.primeSanctums[P-2]=WAIT OF THE WORLD
ultrakill.levels.primeSanctums[P-3]=???

ultrakill.levels.secretLevels[0-S]=SOMETHING WICKED
ultrakill.levels.secretLevels[1-S]=THE WITLESS
ultrakill.levels.secretLevels[2-S]=ALL-IMPERFECT LOVE SONG
ultrakill.levels.secretLevels[4-S]=CLASH OF THE BRANDICOOT
ultrakill.levels.secretLevels[5-S]=I ONLY SAY MORNING
ultrakill.levels.secretLevels[7-S]=HELL BATH NO FURY
ultrakill.levels.secretLevels[8-S]=???
ultrakill.levels.secretLevels[9-S]=???

ultrakill.levels.encores[0-E]=THIS HEAT, AN EVIL HEAT
ultrakill.levels.encores[1-E]=...THEN FELL THE ASHES
ultrakill.levels.encores[2-E]=???
ultrakill.levels.encores[3-E]=???
ultrakill.levels.encores[4-E]=???
ultrakill.levels.encores[5-E]=???
ultrakill.levels.encores[6-E]=???
ultrakill.levels.encores[7-E]=???
ultrakill.levels.encores[8-E]=???
ultrakill.levels.encores[9-E]=???

# Layer names
ultrakill.levels.layers.0=Prelude
ultrakill.levels.layers.1=Limbo
ultrakill.levels.layers.2=Lust
ultrakill.levels.layers.3=Gluttony
ultrakill.levels.layers.4=Greed
ultrakill.levels.layers.5=Wrath
ultrakill.levels.layers.6=Heresy
ultrakill.levels.layers.7=Violence
ultrakill.levels.layers.8=Fraud
ultrakill.levels.layers.9=Treachery
ultrakill.levels.layers.P=Prime

# Ordinals
ultrakill.levels.ordinals.1=First
ultrakill.levels.ordinals.2=Second
ultrakill.levels.ordinals.3=Third
ultrakill.levels.ordinals.4=Fourth
ultrakill.levels.ordinals.S=Secret
ultrakill.levels.ordinals.E=Encore
