# Basic Spring configuration
spring.application.name=ULTRACARDS Web UI
spring.main.banner-mode=off
spring.task.scheduling.shutdown.await-termination=true
spring.task.scheduling.shutdown.await-termination-period=5s

# Server configuration
server.port=6967
server.servlet.context-path=/

# ULTRACARDS Server configuration
app.ultracards.server.url=http://localhost:8080/
app.ultracards.server.await-server-connections-for-x-times=5
app.ultracards.server.check-interval-ms=10000

# Spring MVC configuration
spring.mvc.view.prefix=classpath:/templates/
spring.mvc.view.suffix=.html

# Thymeleaf configuration
# Cache should be disabled for prod and enabled for dev
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Token configuration
app.cookie-token.duration-days=15

# Logging settings
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.com.ultracards=TRACE

